post_install()
{
	echo "Setting lowpoly as default LightDM Theme"
	sed -i 's|greeter-session=.*|greeter-session=lightdm-webkit2-greeter|g' /etc/lightdm/lightdm.conf
	sed -i 's|#greeter-session=|greeter-session=|g' /etc/lightdm/lightdm.conf
	sed -i 's|webkit-theme=.*|webkit-theme=lowpoly|g' /etc/lightdm/lightdm-webkit2-greeter.conf
	sed -i 's|#webkit-theme=|webkit-theme=|g' /etc/lightdm/lightdm-webkit2-greeter.conf
}
